sudo: required
services:
    - docker

before_install:
    - docker build -t siddantgurung/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true siddantgurung/react-docker yarn test
deploy:
    provider: heroku
    app: react-docker-app
    secret_access_key: $HEROKU_DEPLOY_KEY
    access_key_id: $HEROKU_DEPLOY_KEY
    on:
        branch: master
        repo: Siddant/react-docker
