sudo: required
services:
    - docker

before_install:
    - docker build -t siddantgurung/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true siddantgurung/react-docker yarn test
    # language: generic 
# script:
    # - docker run USERNAME/docker-react npm run test -- --coverage