sudo: required
services:
    - docker

before_install:
    - docker build -t siddantgurung/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true siddantgurung/react-docker yarn test
deploy:
    provider: heroku
    api_key:
        secure: $HEROKU_DEPLOY_KEY
        app: react-docker-app
        on:
            branch: master
            repo: Siddant/react-docker
